CREATE PROCEDURE InsertSavingsPlan
@YIELD DECIMAL(4,2),
@BUDGET DECIMAL,
@ACCOUNT_ID INTEGER,
@SAVING_GOAL_ID INTEGER
AS
BEGIN
INSERT INTO SavingPlans (YIELD, BUDGET, ACCOUNT_ID, SAVING_GOAL_ID) 
VALUES (@YIELD, @BUDGET, @ACCOUNT_ID, @SAVING_GOAL_ID)
END
GO

CREATE PROCEDURE InsertBudget
@BALANCE DECIMAL,
@CATEGORY_ID INTEGER,
@PERIOD_BEGIN DATE, 
@ACCOUNT_ID INTEGER, 
@PERIOD_END DATE
AS
BEGIN
INSERT INTO Budgets (BALANCE, CATEGORY_ID, PERIOD_BEGIN, ACCOUNT_ID, PERIOD_END) 
VALUES (@BALANCE, @CATEGORY_ID, @PERIOD_BEGIN, @ACCOUNT_ID, @PERIOD_END)
END
GO

CREATE PROCEDURE InsertTransaction
@TRANSACTION_TIME DATETIME, 
@SUBCATEGORY_ID INTEGER, 
@ACCOUNT_ID INTEGER, 
@AMOUNT DECIMAL, 
@DIRECTION_ID INTEGER, 
@DESCRIPTION VARCHAR(255)
AS
BEGIN
INSERT INTO Transactions (TRANSACTION_TIME, SUBCATEGORY_ID, ACCOUNT_ID, AMOUNT, DIRECTION_ID, [DESCRIPTION]) 
VALUES (@TRANSACTION_TIME, @SUBCATEGORY_ID, @ACCOUNT_ID, @AMOUNT, @DIRECTION_ID, @DESCRIPTION)
END
GO

CREATE PROCEDURE UpdateSavingPlan
@BUDGET DECIMAL,
@ACCOUNT_ID INTEGER,
@YIELD DECIMAL(4,2),
@OLD_BUDGET DECIMAL
AS
BEGIN
UPDATE SavingPlans SET BUDGET=@BUDGET WHERE ACCOUNT_ID=@ACCOUNT_ID AND YIELD=@YIELD AND BUDGET=@OLD_BUDGET
END
GO

CREATE PROCEDURE UpdateBudget
@BALANCE DECIMAL,
@ACCOUNT_ID INTEGER,
@OLD_BALANCE DECIMAL,
@PERIOD_BEGIN DATE,
@PERIOD_END DATE
AS
BEGIN
UPDATE Budgets SET BALANCE=@BALANCE WHERE ACCOUNT_ID=@ACCOUNT_ID AND PERIOD_BEGIN=@PERIOD_BEGIN 
AND BALANCE=@OLD_BALANCE AND PERIOD_END = @PERIOD_END
END
GO

CREATE PROCEDURE DeleteTransaction
@TRANSACTION_TIME DATE,
@ACCOUNT_ID INTEGER,
@AMOUNT DECIMAL
AS
BEGIN
DELETE FROM Transactions WHERE ACCOUNT_ID=@ACCOUNT_ID 
AND TRANSACTION_TIME=@TRANSACTION_TIME AND AMOUNT=@AMOUNT
END
GO

CREATE PROCEDURE DeleteSavingPlan
@YIELD DECIMAL(4,2),
@ACCOUNT_ID INTEGER,
@BUDGET DECIMAL
AS
BEGIN
DELETE FROM SavingPlans WHERE ACCOUNT_ID=@ACCOUNT_ID AND YIELD=@YIELD AND BUDGET=@BUDGET
END
GO

CREATE PROCEDURE DeleteBudget
@PERIOD_END DATE,
@ACCOUNT_ID INTEGER,
@PERIOD_BEGIN DATE
AS
BEGIN
DELETE FROM Budgets WHERE ACCOUNT_ID=@ACCOUNT_ID AND PERIOD_END=@PERIOD_END AND PERIOD_BEGIN=@PERIOD_BEGIN
END
GO