CREATE TABLE Roles (
	ROLE_ID INT IDENTITY PRIMARY KEY ,
	ROLE_NAME VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO Roles (ROLE_NAME) VALUES
('User'),
('Admin');

ALTER TABLE Users 
ADD ROLE_ID INT NOT NULL DEFAULT 1 REFERENCES Roles(ROLE_ID) 