CREATE TABLE [Users] (
	[USER_ID] INTEGER NOT NULL IDENTITY,
	[NAME] VARCHAR(255),
	[EMAIL] VARCHAR(255) UNIQUE CHECK(EMAIL LIKE '%_@_%._%'),
	[PASSWORD_HASH] VARCHAR(255),
	PRIMARY KEY([USER_ID])
);
GO

CREATE TABLE [Accounts] (
	[ACCOUNT_ID] INTEGER NOT NULL IDENTITY,
	[PURPOSE_ID] INTEGER,
	[CURRENCY_ID] INTEGER,
	[BALANCE] DECIMAL(18,2),
	[USER_ID] INTEGER,
	PRIMARY KEY([ACCOUNT_ID])
);
GO

CREATE TABLE [Categories] (
	[CATEGORY_ID] INTEGER NOT NULL IDENTITY,
	[NAME] VARCHAR(255) UNIQUE,
	[PRIORITY_ID] INTEGER,
	[DESCRIPTION] VARCHAR(255),
	PRIMARY KEY([CATEGORY_ID])
);
GO

CREATE TABLE [Subcategories] (
	[SUBCATEGORY_ID] INTEGER NOT NULL IDENTITY,
	[CATEGORY_ID] INTEGER,
	[NAME] VARCHAR(255) UNIQUE,
	PRIMARY KEY([SUBCATEGORY_ID])
);
GO

CREATE TABLE [Transactions] (
	[TRANSACTION_ID] INTEGER NOT NULL IDENTITY,
	[TRANSACTION_TIME] DATE,
	[SUBCATEGORY_ID] INTEGER,
	[ACCOUNT_ID] INTEGER,
	[AMOUNT] DECIMAL(18,2),
	[DIRECTION_ID] INTEGER,
	[DESCRIPTION] VARCHAR(255),
	PRIMARY KEY([TRANSACTION_ID]),
	CONSTRAINT [CHK_Transaction_Amount_Direction] CHECK (
		([DIRECTION_ID] = 1 AND [AMOUNT] > 0) OR 
		([DIRECTION_ID] = 2 AND [AMOUNT] < 0)
	)
);
GO

CREATE TABLE [SavingPlans] (
	[SAVING_PLAN_ID] INTEGER NOT NULL IDENTITY,
	[YIELD] DECIMAL(4,2),
	[BUDGET] DECIMAL(18,2),
	[ACCOUNT_ID] INTEGER,
	[SAVING_GOAL_ID] INTEGER,
	PRIMARY KEY([SAVING_PLAN_ID])
);
GO

CREATE TABLE [Currency] (
	[CURRENCY_ID] INTEGER NOT NULL IDENTITY,
	[NAME] CHAR(3) UNIQUE,
	PRIMARY KEY([CURRENCY_ID])
);
GO

CREATE TABLE [Budgets] (
	[BUDGET_ID] INTEGER NOT NULL IDENTITY,
	[BALANCE] DECIMAL(18,2),
	[CATEGORY_ID] INTEGER,
	[PERIOD_BEGIN] DATE,
	[ACCOUNT_ID] INTEGER,
	[PERIOD_END] DATE,
	PRIMARY KEY([BUDGET_ID])
);
GO

CREATE TABLE [RecurringPayments] (
	[RECURRING_PAYMENT_ID] INTEGER NOT NULL IDENTITY,
	[COMPANY_NAME] VARCHAR(255),
	[PRICE] DECIMAL(18,2),
	[SUBCATEGORY_ID] INTEGER,
	[DUE_DATE] DATE,
	[ACCOUNT_ID] INTEGER,
	[FREQUENCY_ID] INTEGER,
	[CURRENCY_ID] INTEGER,
	PRIMARY KEY([RECURRING_PAYMENT_ID])
);
GO

CREATE TABLE [Loans] (
	[LOAN_ID] INTEGER NOT NULL IDENTITY,
	[INTEREST] DECIMAL(5,2),
	[VALUE] DECIMAL(18,2),
	[ACCOUNT_ID] INTEGER,
	PRIMARY KEY([LOAN_ID])
);
GO

CREATE TABLE [Priorities] (
	[PRIORITY_ID] INTEGER NOT NULL IDENTITY,
	[NAME] VARCHAR(255),
	PRIMARY KEY([PRIORITY_ID])
);
GO

CREATE TABLE [Purposes] (
	[PURPOSE_ID] INTEGER NOT NULL IDENTITY,
	[NAME] VARCHAR(255),
	PRIMARY KEY([PURPOSE_ID])
);
GO

CREATE TABLE [SavingGoals] (
	[SAVING_GOAL_ID] INTEGER NOT NULL IDENTITY,
	[NAME] VARCHAR(255),
	PRIMARY KEY([SAVING_GOAL_ID])
);
GO

CREATE TABLE [Direction] (
	[DIRECTION_ID] INTEGER NOT NULL IDENTITY,
	[TYPE] VARCHAR(255),
	PRIMARY KEY([DIRECTION_ID])
);
GO

CREATE TABLE [Frequencies] (
	[FREQUENCY_ID] INTEGER NOT NULL IDENTITY,
	[NAME] VARCHAR(255),
	PRIMARY KEY([FREQUENCY_ID])
);
GO

CREATE TABLE [Budget_Transactions] (
	[BUDGET_ID] INTEGER NOT NULL,
	[TRANSACTION_ID] INTEGER NOT NULL,
	PRIMARY KEY([BUDGET_ID], [TRANSACTION_ID])
);
GO

ALTER TABLE [Accounts] 
	ADD FOREIGN KEY([USER_ID]) REFERENCES [Users]([USER_ID]);
GO

ALTER TABLE [Accounts] 
	ADD FOREIGN KEY([PURPOSE_ID]) REFERENCES [Purposes]([PURPOSE_ID]);
GO

ALTER TABLE [Accounts] 
	ADD FOREIGN KEY([CURRENCY_ID]) REFERENCES [Currency]([CURRENCY_ID]);
GO

ALTER TABLE [Subcategories] 
	ADD FOREIGN KEY([CATEGORY_ID]) REFERENCES [Categories]([CATEGORY_ID]);
GO

ALTER TABLE [Categories] 
	ADD FOREIGN KEY([PRIORITY_ID]) REFERENCES [Priorities]([PRIORITY_ID]);
GO

ALTER TABLE [Transactions] 
	ADD FOREIGN KEY([ACCOUNT_ID]) REFERENCES [Accounts]([ACCOUNT_ID]);
GO

ALTER TABLE [Transactions] 
	ADD FOREIGN KEY([SUBCATEGORY_ID]) REFERENCES [Subcategories]([SUBCATEGORY_ID]);
GO

ALTER TABLE [Transactions] 
	ADD FOREIGN KEY([DIRECTION_ID]) REFERENCES [Direction]([DIRECTION_ID]);
GO

ALTER TABLE [RecurringPayments] 
	ADD FOREIGN KEY([ACCOUNT_ID]) REFERENCES [Accounts]([ACCOUNT_ID]);
GO

ALTER TABLE [RecurringPayments] 
	ADD FOREIGN KEY([FREQUENCY_ID]) REFERENCES [Frequencies]([FREQUENCY_ID]);
GO

ALTER TABLE [RecurringPayments] 
	ADD FOREIGN KEY([CURRENCY_ID]) REFERENCES [Currency]([CURRENCY_ID]);
GO

ALTER TABLE [Loans] 
	ADD FOREIGN KEY([ACCOUNT_ID]) REFERENCES [Accounts]([ACCOUNT_ID]);
GO

ALTER TABLE [SavingPlans] 
	ADD FOREIGN KEY([SAVING_GOAL_ID]) REFERENCES [SavingGoals]([SAVING_GOAL_ID]);
GO

ALTER TABLE [SavingPlans] 
	ADD FOREIGN KEY([ACCOUNT_ID]) REFERENCES [Accounts]([ACCOUNT_ID]);
GO

ALTER TABLE [Budgets] 
	ADD FOREIGN KEY([CATEGORY_ID]) REFERENCES [Categories]([CATEGORY_ID]);
GO

ALTER TABLE [Budgets] 
	ADD FOREIGN KEY([ACCOUNT_ID]) REFERENCES [Accounts]([ACCOUNT_ID]);
GO

ALTER TABLE [Budget_Transactions] 
	ADD FOREIGN KEY([TRANSACTION_ID]) REFERENCES [Transactions]([TRANSACTION_ID]);
GO

ALTER TABLE [Budget_Transactions] 
	ADD FOREIGN KEY([BUDGET_ID]) REFERENCES [Budgets]([BUDGET_ID]);
GO